name: New Feature
description: Suggest a new feature for this project
labels: ["enhancement"]
type: Feature
projects: ["City-Reach/2"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Describe the problem or use case..."
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What are the requirements for this feature?
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true
