name: Task
description: Create a task for the project
labels: ["enhancement"]
type: Task
projects: ["City-Reach/2"]

body:
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the requirements that define when this task is complete
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or information relevant to this task
