/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as OOrgSlugRouteRouteImport } from './routes/o.$orgSlug/route'
import { Route as OOrgSlugIndexRouteImport } from './routes/o.$orgSlug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OOrgSlugTestimonialsRouteRouteImport } from './routes/o.$orgSlug/testimonials/route'
import { Route as OOrgSlugDashboardRouteRouteImport } from './routes/o.$orgSlug/_dashboard/route'
import { Route as OOrgSlugTestimonialsIndexRouteImport } from './routes/o.$orgSlug/testimonials/index'
import { Route as OOrgSlugTestimonialsIdRouteImport } from './routes/o.$orgSlug/testimonials/$id'
import { Route as OOrgSlugDashboardSettingsRouteImport } from './routes/o.$orgSlug/_dashboard/settings'
import { Route as OOrgSlugDashboardModeratorRouteImport } from './routes/o.$orgSlug/_dashboard/moderator'
import { Route as OOrgSlugDashboardMembersRouteImport } from './routes/o.$orgSlug/_dashboard/members'
import { Route as OOrgSlugTestimonialsTmpIdRouteImport } from './routes/o.$orgSlug/testimonials/tmp.$id'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const OOrgSlugRouteRoute = OOrgSlugRouteRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugIndexRoute = OOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugTestimonialsRouteRoute =
  OOrgSlugTestimonialsRouteRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => OOrgSlugRouteRoute,
  } as any)
const OOrgSlugDashboardRouteRoute = OOrgSlugDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugTestimonialsIndexRoute =
  OOrgSlugTestimonialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgSlugTestimonialsRouteRoute,
  } as any)
const OOrgSlugTestimonialsIdRoute = OOrgSlugTestimonialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OOrgSlugTestimonialsRouteRoute,
} as any)
const OOrgSlugDashboardSettingsRoute =
  OOrgSlugDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardModeratorRoute =
  OOrgSlugDashboardModeratorRouteImport.update({
    id: '/moderator',
    path: '/moderator',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardMembersRoute =
  OOrgSlugDashboardMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugTestimonialsTmpIdRoute =
  OOrgSlugTestimonialsTmpIdRouteImport.update({
    id: '/tmp/$id',
    path: '/tmp/$id',
    getParentRoute: () => OOrgSlugTestimonialsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugDashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/o/$orgSlug/testimonials': typeof OOrgSlugTestimonialsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/moderator': typeof OOrgSlugDashboardModeratorRoute
  '/o/$orgSlug/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/testimonials/$id': typeof OOrgSlugTestimonialsIdRoute
  '/o/$orgSlug/testimonials/': typeof OOrgSlugTestimonialsIndexRoute
  '/o/$orgSlug/testimonials/tmp/$id': typeof OOrgSlugTestimonialsTmpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-out': typeof SignOutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin': typeof AdminIndexRoute
  '/o/$orgSlug': typeof OOrgSlugIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgSlug/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/moderator': typeof OOrgSlugDashboardModeratorRoute
  '/o/$orgSlug/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/testimonials/$id': typeof OOrgSlugTestimonialsIdRoute
  '/o/$orgSlug/testimonials': typeof OOrgSlugTestimonialsIndexRoute
  '/o/$orgSlug/testimonials/tmp/$id': typeof OOrgSlugTestimonialsTmpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/o/$orgSlug/_dashboard': typeof OOrgSlugDashboardRouteRouteWithChildren
  '/o/$orgSlug/testimonials': typeof OOrgSlugTestimonialsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/_dashboard/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/_dashboard/moderator': typeof OOrgSlugDashboardModeratorRoute
  '/o/$orgSlug/_dashboard/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/testimonials/$id': typeof OOrgSlugTestimonialsIdRoute
  '/o/$orgSlug/testimonials/': typeof OOrgSlugTestimonialsIndexRoute
  '/o/$orgSlug/testimonials/tmp/$id': typeof OOrgSlugTestimonialsTmpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/admin/organizations'
    | '/admin/'
    | '/o/$orgSlug/testimonials'
    | '/api/auth/$'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/members'
    | '/o/$orgSlug/moderator'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/testimonials/$id'
    | '/o/$orgSlug/testimonials/'
    | '/o/$orgSlug/testimonials/tmp/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-out'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/admin/organizations'
    | '/admin'
    | '/o/$orgSlug'
    | '/api/auth/$'
    | '/o/$orgSlug/members'
    | '/o/$orgSlug/moderator'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/testimonials/$id'
    | '/o/$orgSlug/testimonials'
    | '/o/$orgSlug/testimonials/tmp/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/admin/organizations'
    | '/admin/'
    | '/o/$orgSlug/_dashboard'
    | '/o/$orgSlug/testimonials'
    | '/api/auth/$'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/_dashboard/members'
    | '/o/$orgSlug/_dashboard/moderator'
    | '/o/$orgSlug/_dashboard/settings'
    | '/o/$orgSlug/testimonials/$id'
    | '/o/$orgSlug/testimonials/'
    | '/o/$orgSlug/testimonials/tmp/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SignOutRoute: typeof SignOutRoute
  OOrgSlugRouteRoute: typeof OOrgSlugRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/o/$orgSlug': {
      id: '/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/': {
      id: '/o/$orgSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugIndexRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/testimonials': {
      id: '/o/$orgSlug/testimonials'
      path: '/testimonials'
      fullPath: '/o/$orgSlug/testimonials'
      preLoaderRoute: typeof OOrgSlugTestimonialsRouteRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/_dashboard': {
      id: '/o/$orgSlug/_dashboard'
      path: ''
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugDashboardRouteRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/testimonials/': {
      id: '/o/$orgSlug/testimonials/'
      path: '/'
      fullPath: '/o/$orgSlug/testimonials/'
      preLoaderRoute: typeof OOrgSlugTestimonialsIndexRouteImport
      parentRoute: typeof OOrgSlugTestimonialsRouteRoute
    }
    '/o/$orgSlug/testimonials/$id': {
      id: '/o/$orgSlug/testimonials/$id'
      path: '/$id'
      fullPath: '/o/$orgSlug/testimonials/$id'
      preLoaderRoute: typeof OOrgSlugTestimonialsIdRouteImport
      parentRoute: typeof OOrgSlugTestimonialsRouteRoute
    }
    '/o/$orgSlug/_dashboard/settings': {
      id: '/o/$orgSlug/_dashboard/settings'
      path: '/settings'
      fullPath: '/o/$orgSlug/settings'
      preLoaderRoute: typeof OOrgSlugDashboardSettingsRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_dashboard/moderator': {
      id: '/o/$orgSlug/_dashboard/moderator'
      path: '/moderator'
      fullPath: '/o/$orgSlug/moderator'
      preLoaderRoute: typeof OOrgSlugDashboardModeratorRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_dashboard/members': {
      id: '/o/$orgSlug/_dashboard/members'
      path: '/members'
      fullPath: '/o/$orgSlug/members'
      preLoaderRoute: typeof OOrgSlugDashboardMembersRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/testimonials/tmp/$id': {
      id: '/o/$orgSlug/testimonials/tmp/$id'
      path: '/tmp/$id'
      fullPath: '/o/$orgSlug/testimonials/tmp/$id'
      preLoaderRoute: typeof OOrgSlugTestimonialsTmpIdRouteImport
      parentRoute: typeof OOrgSlugTestimonialsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OOrgSlugDashboardRouteRouteChildren {
  OOrgSlugDashboardMembersRoute: typeof OOrgSlugDashboardMembersRoute
  OOrgSlugDashboardModeratorRoute: typeof OOrgSlugDashboardModeratorRoute
  OOrgSlugDashboardSettingsRoute: typeof OOrgSlugDashboardSettingsRoute
}

const OOrgSlugDashboardRouteRouteChildren: OOrgSlugDashboardRouteRouteChildren =
  {
    OOrgSlugDashboardMembersRoute: OOrgSlugDashboardMembersRoute,
    OOrgSlugDashboardModeratorRoute: OOrgSlugDashboardModeratorRoute,
    OOrgSlugDashboardSettingsRoute: OOrgSlugDashboardSettingsRoute,
  }

const OOrgSlugDashboardRouteRouteWithChildren =
  OOrgSlugDashboardRouteRoute._addFileChildren(
    OOrgSlugDashboardRouteRouteChildren,
  )

interface OOrgSlugTestimonialsRouteRouteChildren {
  OOrgSlugTestimonialsIdRoute: typeof OOrgSlugTestimonialsIdRoute
  OOrgSlugTestimonialsIndexRoute: typeof OOrgSlugTestimonialsIndexRoute
  OOrgSlugTestimonialsTmpIdRoute: typeof OOrgSlugTestimonialsTmpIdRoute
}

const OOrgSlugTestimonialsRouteRouteChildren: OOrgSlugTestimonialsRouteRouteChildren =
  {
    OOrgSlugTestimonialsIdRoute: OOrgSlugTestimonialsIdRoute,
    OOrgSlugTestimonialsIndexRoute: OOrgSlugTestimonialsIndexRoute,
    OOrgSlugTestimonialsTmpIdRoute: OOrgSlugTestimonialsTmpIdRoute,
  }

const OOrgSlugTestimonialsRouteRouteWithChildren =
  OOrgSlugTestimonialsRouteRoute._addFileChildren(
    OOrgSlugTestimonialsRouteRouteChildren,
  )

interface OOrgSlugRouteRouteChildren {
  OOrgSlugDashboardRouteRoute: typeof OOrgSlugDashboardRouteRouteWithChildren
  OOrgSlugTestimonialsRouteRoute: typeof OOrgSlugTestimonialsRouteRouteWithChildren
  OOrgSlugIndexRoute: typeof OOrgSlugIndexRoute
}

const OOrgSlugRouteRouteChildren: OOrgSlugRouteRouteChildren = {
  OOrgSlugDashboardRouteRoute: OOrgSlugDashboardRouteRouteWithChildren,
  OOrgSlugTestimonialsRouteRoute: OOrgSlugTestimonialsRouteRouteWithChildren,
  OOrgSlugIndexRoute: OOrgSlugIndexRoute,
}

const OOrgSlugRouteRouteWithChildren = OOrgSlugRouteRoute._addFileChildren(
  OOrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SignOutRoute: SignOutRoute,
  OOrgSlugRouteRoute: OOrgSlugRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
