/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as OOrgSlugRouteRouteImport } from './routes/o.$orgSlug/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OOrgSlugDashboardRouteRouteImport } from './routes/o.$orgSlug/dashboard/route'
import { Route as OOrgSlugPublicRouteRouteImport } from './routes/o.$orgSlug/_public/route'
import { Route as OOrgSlugDashboardIndexRouteImport } from './routes/o.$orgSlug/dashboard/index'
import { Route as OOrgSlugPublicIndexRouteImport } from './routes/o.$orgSlug/_public/index'
import { Route as OOrgSlugDashboardTestimonialsRouteImport } from './routes/o.$orgSlug/dashboard/testimonials'
import { Route as OOrgSlugDashboardSettingsRouteImport } from './routes/o.$orgSlug/dashboard/settings'
import { Route as OOrgSlugDashboardMembersRouteImport } from './routes/o.$orgSlug/dashboard/members'
import { Route as OOrgSlugPublicTestimonialsRouteRouteImport } from './routes/o.$orgSlug/_public/testimonials/route'
import { Route as OOrgSlugPublicTestimonialsIndexRouteImport } from './routes/o.$orgSlug/_public/testimonials/index'
import { Route as OOrgSlugPublicTestimonialsIdRouteImport } from './routes/o.$orgSlug/_public/testimonials/$id'
import { Route as OOrgSlugPublicTestimonialsTmpIdRouteImport } from './routes/o.$orgSlug/_public/testimonials/tmp.$id'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const OOrgSlugRouteRoute = OOrgSlugRouteRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugDashboardRouteRoute = OOrgSlugDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugPublicRouteRoute = OOrgSlugPublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugDashboardIndexRoute = OOrgSlugDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgSlugDashboardRouteRoute,
} as any)
const OOrgSlugPublicIndexRoute = OOrgSlugPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgSlugPublicRouteRoute,
} as any)
const OOrgSlugDashboardTestimonialsRoute =
  OOrgSlugDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardSettingsRoute =
  OOrgSlugDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardMembersRoute =
  OOrgSlugDashboardMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugPublicTestimonialsRouteRoute =
  OOrgSlugPublicTestimonialsRouteRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => OOrgSlugPublicRouteRoute,
  } as any)
const OOrgSlugPublicTestimonialsIndexRoute =
  OOrgSlugPublicTestimonialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgSlugPublicTestimonialsRouteRoute,
  } as any)
const OOrgSlugPublicTestimonialsIdRoute =
  OOrgSlugPublicTestimonialsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => OOrgSlugPublicTestimonialsRouteRoute,
  } as any)
const OOrgSlugPublicTestimonialsTmpIdRoute =
  OOrgSlugPublicTestimonialsTmpIdRouteImport.update({
    id: '/tmp/$id',
    path: '/tmp/$id',
    getParentRoute: () => OOrgSlugPublicTestimonialsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugPublicRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/o/$orgSlug/dashboard': typeof OOrgSlugDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgSlug/testimonials': typeof OOrgSlugPublicTestimonialsRouteRouteWithChildren
  '/o/$orgSlug/dashboard/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/dashboard/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/dashboard/testimonials': typeof OOrgSlugDashboardTestimonialsRoute
  '/o/$orgSlug/': typeof OOrgSlugPublicIndexRoute
  '/o/$orgSlug/dashboard/': typeof OOrgSlugDashboardIndexRoute
  '/o/$orgSlug/testimonials/$id': typeof OOrgSlugPublicTestimonialsIdRoute
  '/o/$orgSlug/testimonials/': typeof OOrgSlugPublicTestimonialsIndexRoute
  '/o/$orgSlug/testimonials/tmp/$id': typeof OOrgSlugPublicTestimonialsTmpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugPublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgSlug/dashboard/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/dashboard/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/dashboard/testimonials': typeof OOrgSlugDashboardTestimonialsRoute
  '/o/$orgSlug/dashboard': typeof OOrgSlugDashboardIndexRoute
  '/o/$orgSlug/testimonials/$id': typeof OOrgSlugPublicTestimonialsIdRoute
  '/o/$orgSlug/testimonials': typeof OOrgSlugPublicTestimonialsIndexRoute
  '/o/$orgSlug/testimonials/tmp/$id': typeof OOrgSlugPublicTestimonialsTmpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/o/$orgSlug/_public': typeof OOrgSlugPublicRouteRouteWithChildren
  '/o/$orgSlug/dashboard': typeof OOrgSlugDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgSlug/_public/testimonials': typeof OOrgSlugPublicTestimonialsRouteRouteWithChildren
  '/o/$orgSlug/dashboard/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/dashboard/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/dashboard/testimonials': typeof OOrgSlugDashboardTestimonialsRoute
  '/o/$orgSlug/_public/': typeof OOrgSlugPublicIndexRoute
  '/o/$orgSlug/dashboard/': typeof OOrgSlugDashboardIndexRoute
  '/o/$orgSlug/_public/testimonials/$id': typeof OOrgSlugPublicTestimonialsIdRoute
  '/o/$orgSlug/_public/testimonials/': typeof OOrgSlugPublicTestimonialsIndexRoute
  '/o/$orgSlug/_public/testimonials/tmp/$id': typeof OOrgSlugPublicTestimonialsTmpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/admin/organizations'
    | '/admin/'
    | '/o/$orgSlug/dashboard'
    | '/api/auth/$'
    | '/o/$orgSlug/testimonials'
    | '/o/$orgSlug/dashboard/members'
    | '/o/$orgSlug/dashboard/settings'
    | '/o/$orgSlug/dashboard/testimonials'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/dashboard/'
    | '/o/$orgSlug/testimonials/$id'
    | '/o/$orgSlug/testimonials/'
    | '/o/$orgSlug/testimonials/tmp/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/admin/organizations'
    | '/admin'
    | '/api/auth/$'
    | '/o/$orgSlug/dashboard/members'
    | '/o/$orgSlug/dashboard/settings'
    | '/o/$orgSlug/dashboard/testimonials'
    | '/o/$orgSlug/dashboard'
    | '/o/$orgSlug/testimonials/$id'
    | '/o/$orgSlug/testimonials'
    | '/o/$orgSlug/testimonials/tmp/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/admin/organizations'
    | '/admin/'
    | '/o/$orgSlug/_public'
    | '/o/$orgSlug/dashboard'
    | '/api/auth/$'
    | '/o/$orgSlug/_public/testimonials'
    | '/o/$orgSlug/dashboard/members'
    | '/o/$orgSlug/dashboard/settings'
    | '/o/$orgSlug/dashboard/testimonials'
    | '/o/$orgSlug/_public/'
    | '/o/$orgSlug/dashboard/'
    | '/o/$orgSlug/_public/testimonials/$id'
    | '/o/$orgSlug/_public/testimonials/'
    | '/o/$orgSlug/_public/testimonials/tmp/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SignOutRoute: typeof SignOutRoute
  OOrgSlugRouteRoute: typeof OOrgSlugRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/o/$orgSlug': {
      id: '/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/dashboard': {
      id: '/o/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/o/$orgSlug/dashboard'
      preLoaderRoute: typeof OOrgSlugDashboardRouteRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/_public': {
      id: '/o/$orgSlug/_public'
      path: ''
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugPublicRouteRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/dashboard/': {
      id: '/o/$orgSlug/dashboard/'
      path: '/'
      fullPath: '/o/$orgSlug/dashboard/'
      preLoaderRoute: typeof OOrgSlugDashboardIndexRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_public/': {
      id: '/o/$orgSlug/_public/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugPublicIndexRouteImport
      parentRoute: typeof OOrgSlugPublicRouteRoute
    }
    '/o/$orgSlug/dashboard/testimonials': {
      id: '/o/$orgSlug/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/o/$orgSlug/dashboard/testimonials'
      preLoaderRoute: typeof OOrgSlugDashboardTestimonialsRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/dashboard/settings': {
      id: '/o/$orgSlug/dashboard/settings'
      path: '/settings'
      fullPath: '/o/$orgSlug/dashboard/settings'
      preLoaderRoute: typeof OOrgSlugDashboardSettingsRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/dashboard/members': {
      id: '/o/$orgSlug/dashboard/members'
      path: '/members'
      fullPath: '/o/$orgSlug/dashboard/members'
      preLoaderRoute: typeof OOrgSlugDashboardMembersRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_public/testimonials': {
      id: '/o/$orgSlug/_public/testimonials'
      path: '/testimonials'
      fullPath: '/o/$orgSlug/testimonials'
      preLoaderRoute: typeof OOrgSlugPublicTestimonialsRouteRouteImport
      parentRoute: typeof OOrgSlugPublicRouteRoute
    }
    '/o/$orgSlug/_public/testimonials/': {
      id: '/o/$orgSlug/_public/testimonials/'
      path: '/'
      fullPath: '/o/$orgSlug/testimonials/'
      preLoaderRoute: typeof OOrgSlugPublicTestimonialsIndexRouteImport
      parentRoute: typeof OOrgSlugPublicTestimonialsRouteRoute
    }
    '/o/$orgSlug/_public/testimonials/$id': {
      id: '/o/$orgSlug/_public/testimonials/$id'
      path: '/$id'
      fullPath: '/o/$orgSlug/testimonials/$id'
      preLoaderRoute: typeof OOrgSlugPublicTestimonialsIdRouteImport
      parentRoute: typeof OOrgSlugPublicTestimonialsRouteRoute
    }
    '/o/$orgSlug/_public/testimonials/tmp/$id': {
      id: '/o/$orgSlug/_public/testimonials/tmp/$id'
      path: '/tmp/$id'
      fullPath: '/o/$orgSlug/testimonials/tmp/$id'
      preLoaderRoute: typeof OOrgSlugPublicTestimonialsTmpIdRouteImport
      parentRoute: typeof OOrgSlugPublicTestimonialsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OOrgSlugPublicTestimonialsRouteRouteChildren {
  OOrgSlugPublicTestimonialsIdRoute: typeof OOrgSlugPublicTestimonialsIdRoute
  OOrgSlugPublicTestimonialsIndexRoute: typeof OOrgSlugPublicTestimonialsIndexRoute
  OOrgSlugPublicTestimonialsTmpIdRoute: typeof OOrgSlugPublicTestimonialsTmpIdRoute
}

const OOrgSlugPublicTestimonialsRouteRouteChildren: OOrgSlugPublicTestimonialsRouteRouteChildren =
  {
    OOrgSlugPublicTestimonialsIdRoute: OOrgSlugPublicTestimonialsIdRoute,
    OOrgSlugPublicTestimonialsIndexRoute: OOrgSlugPublicTestimonialsIndexRoute,
    OOrgSlugPublicTestimonialsTmpIdRoute: OOrgSlugPublicTestimonialsTmpIdRoute,
  }

const OOrgSlugPublicTestimonialsRouteRouteWithChildren =
  OOrgSlugPublicTestimonialsRouteRoute._addFileChildren(
    OOrgSlugPublicTestimonialsRouteRouteChildren,
  )

interface OOrgSlugPublicRouteRouteChildren {
  OOrgSlugPublicTestimonialsRouteRoute: typeof OOrgSlugPublicTestimonialsRouteRouteWithChildren
  OOrgSlugPublicIndexRoute: typeof OOrgSlugPublicIndexRoute
}

const OOrgSlugPublicRouteRouteChildren: OOrgSlugPublicRouteRouteChildren = {
  OOrgSlugPublicTestimonialsRouteRoute:
    OOrgSlugPublicTestimonialsRouteRouteWithChildren,
  OOrgSlugPublicIndexRoute: OOrgSlugPublicIndexRoute,
}

const OOrgSlugPublicRouteRouteWithChildren =
  OOrgSlugPublicRouteRoute._addFileChildren(OOrgSlugPublicRouteRouteChildren)

interface OOrgSlugDashboardRouteRouteChildren {
  OOrgSlugDashboardMembersRoute: typeof OOrgSlugDashboardMembersRoute
  OOrgSlugDashboardSettingsRoute: typeof OOrgSlugDashboardSettingsRoute
  OOrgSlugDashboardTestimonialsRoute: typeof OOrgSlugDashboardTestimonialsRoute
  OOrgSlugDashboardIndexRoute: typeof OOrgSlugDashboardIndexRoute
}

const OOrgSlugDashboardRouteRouteChildren: OOrgSlugDashboardRouteRouteChildren =
  {
    OOrgSlugDashboardMembersRoute: OOrgSlugDashboardMembersRoute,
    OOrgSlugDashboardSettingsRoute: OOrgSlugDashboardSettingsRoute,
    OOrgSlugDashboardTestimonialsRoute: OOrgSlugDashboardTestimonialsRoute,
    OOrgSlugDashboardIndexRoute: OOrgSlugDashboardIndexRoute,
  }

const OOrgSlugDashboardRouteRouteWithChildren =
  OOrgSlugDashboardRouteRoute._addFileChildren(
    OOrgSlugDashboardRouteRouteChildren,
  )

interface OOrgSlugRouteRouteChildren {
  OOrgSlugPublicRouteRoute: typeof OOrgSlugPublicRouteRouteWithChildren
  OOrgSlugDashboardRouteRoute: typeof OOrgSlugDashboardRouteRouteWithChildren
}

const OOrgSlugRouteRouteChildren: OOrgSlugRouteRouteChildren = {
  OOrgSlugPublicRouteRoute: OOrgSlugPublicRouteRouteWithChildren,
  OOrgSlugDashboardRouteRoute: OOrgSlugDashboardRouteRouteWithChildren,
}

const OOrgSlugRouteRouteWithChildren = OOrgSlugRouteRoute._addFileChildren(
  OOrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SignOutRoute: SignOutRoute,
  OOrgSlugRouteRoute: OOrgSlugRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
