/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as TestimonialsRouteRouteImport } from './routes/testimonials/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestimonialsIdRouteImport } from './routes/testimonials/$id'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as OOrgSlugRouteRouteImport } from './routes/o.$orgSlug/route'
import { Route as OOrgSlugIndexRouteImport } from './routes/o.$orgSlug/index'
import { Route as TestimonialsTmpIdRouteImport } from './routes/testimonials/tmp.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OOrgSlugDashboardRouteRouteImport } from './routes/o.$orgSlug/_dashboard/route'
import { Route as OOrgSlugDashboardTestimonialsRouteImport } from './routes/o.$orgSlug/_dashboard/testimonials'
import { Route as OOrgSlugDashboardSettingsRouteImport } from './routes/o.$orgSlug/_dashboard/settings'
import { Route as OOrgSlugDashboardModeratorRouteImport } from './routes/o.$orgSlug/_dashboard/moderator'
import { Route as OOrgSlugDashboardMembersRouteImport } from './routes/o.$orgSlug/_dashboard/members'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRouteRoute = TestimonialsRouteRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TestimonialsIdRoute = TestimonialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const OOrgSlugRouteRoute = OOrgSlugRouteRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugIndexRoute = OOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const TestimonialsTmpIdRoute = TestimonialsTmpIdRouteImport.update({
  id: '/tmp/$id',
  path: '/tmp/$id',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugDashboardRouteRoute = OOrgSlugDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugDashboardTestimonialsRoute =
  OOrgSlugDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardSettingsRoute =
  OOrgSlugDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardModeratorRoute =
  OOrgSlugDashboardModeratorRouteImport.update({
    id: '/moderator',
    path: '/moderator',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)
const OOrgSlugDashboardMembersRoute =
  OOrgSlugDashboardMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OOrgSlugDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/testimonials': typeof TestimonialsRouteRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugDashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/testimonials/$id': typeof TestimonialsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/testimonials/tmp/$id': typeof TestimonialsTmpIdRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/moderator': typeof OOrgSlugDashboardModeratorRoute
  '/o/$orgSlug/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/testimonials': typeof OOrgSlugDashboardTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-out': typeof SignOutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/testimonials/$id': typeof TestimonialsIdRoute
  '/admin': typeof AdminIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/o/$orgSlug': typeof OOrgSlugIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/testimonials/tmp/$id': typeof TestimonialsTmpIdRoute
  '/o/$orgSlug/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/moderator': typeof OOrgSlugDashboardModeratorRoute
  '/o/$orgSlug/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/testimonials': typeof OOrgSlugDashboardTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/testimonials': typeof TestimonialsRouteRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/o/$orgSlug': typeof OOrgSlugRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/testimonials/$id': typeof TestimonialsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/o/$orgSlug/_dashboard': typeof OOrgSlugDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/testimonials/tmp/$id': typeof TestimonialsTmpIdRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/_dashboard/members': typeof OOrgSlugDashboardMembersRoute
  '/o/$orgSlug/_dashboard/moderator': typeof OOrgSlugDashboardModeratorRoute
  '/o/$orgSlug/_dashboard/settings': typeof OOrgSlugDashboardSettingsRoute
  '/o/$orgSlug/_dashboard/testimonials': typeof OOrgSlugDashboardTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/testimonials'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/admin/organizations'
    | '/testimonials/$id'
    | '/admin/'
    | '/testimonials/'
    | '/api/auth/$'
    | '/testimonials/tmp/$id'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/members'
    | '/o/$orgSlug/moderator'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-out'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/admin/organizations'
    | '/testimonials/$id'
    | '/admin'
    | '/testimonials'
    | '/o/$orgSlug'
    | '/api/auth/$'
    | '/testimonials/tmp/$id'
    | '/o/$orgSlug/members'
    | '/o/$orgSlug/moderator'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/testimonials'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/testimonials'
    | '/sign-out'
    | '/o/$orgSlug'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/admin/organizations'
    | '/testimonials/$id'
    | '/admin/'
    | '/testimonials/'
    | '/o/$orgSlug/_dashboard'
    | '/api/auth/$'
    | '/testimonials/tmp/$id'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/_dashboard/members'
    | '/o/$orgSlug/_dashboard/moderator'
    | '/o/$orgSlug/_dashboard/settings'
    | '/o/$orgSlug/_dashboard/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TestimonialsRouteRoute: typeof TestimonialsRouteRouteWithChildren
  SignOutRoute: typeof SignOutRoute
  OOrgSlugRouteRoute: typeof OOrgSlugRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/testimonials/$id': {
      id: '/testimonials/$id'
      path: '/$id'
      fullPath: '/testimonials/$id'
      preLoaderRoute: typeof TestimonialsIdRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/o/$orgSlug': {
      id: '/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/': {
      id: '/o/$orgSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugIndexRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/testimonials/tmp/$id': {
      id: '/testimonials/tmp/$id'
      path: '/tmp/$id'
      fullPath: '/testimonials/tmp/$id'
      preLoaderRoute: typeof TestimonialsTmpIdRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/_dashboard': {
      id: '/o/$orgSlug/_dashboard'
      path: ''
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugDashboardRouteRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/_dashboard/testimonials': {
      id: '/o/$orgSlug/_dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/o/$orgSlug/testimonials'
      preLoaderRoute: typeof OOrgSlugDashboardTestimonialsRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_dashboard/settings': {
      id: '/o/$orgSlug/_dashboard/settings'
      path: '/settings'
      fullPath: '/o/$orgSlug/settings'
      preLoaderRoute: typeof OOrgSlugDashboardSettingsRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_dashboard/moderator': {
      id: '/o/$orgSlug/_dashboard/moderator'
      path: '/moderator'
      fullPath: '/o/$orgSlug/moderator'
      preLoaderRoute: typeof OOrgSlugDashboardModeratorRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
    '/o/$orgSlug/_dashboard/members': {
      id: '/o/$orgSlug/_dashboard/members'
      path: '/members'
      fullPath: '/o/$orgSlug/members'
      preLoaderRoute: typeof OOrgSlugDashboardMembersRouteImport
      parentRoute: typeof OOrgSlugDashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TestimonialsRouteRouteChildren {
  TestimonialsIdRoute: typeof TestimonialsIdRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
  TestimonialsTmpIdRoute: typeof TestimonialsTmpIdRoute
}

const TestimonialsRouteRouteChildren: TestimonialsRouteRouteChildren = {
  TestimonialsIdRoute: TestimonialsIdRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
  TestimonialsTmpIdRoute: TestimonialsTmpIdRoute,
}

const TestimonialsRouteRouteWithChildren =
  TestimonialsRouteRoute._addFileChildren(TestimonialsRouteRouteChildren)

interface OOrgSlugDashboardRouteRouteChildren {
  OOrgSlugDashboardMembersRoute: typeof OOrgSlugDashboardMembersRoute
  OOrgSlugDashboardModeratorRoute: typeof OOrgSlugDashboardModeratorRoute
  OOrgSlugDashboardSettingsRoute: typeof OOrgSlugDashboardSettingsRoute
  OOrgSlugDashboardTestimonialsRoute: typeof OOrgSlugDashboardTestimonialsRoute
}

const OOrgSlugDashboardRouteRouteChildren: OOrgSlugDashboardRouteRouteChildren =
  {
    OOrgSlugDashboardMembersRoute: OOrgSlugDashboardMembersRoute,
    OOrgSlugDashboardModeratorRoute: OOrgSlugDashboardModeratorRoute,
    OOrgSlugDashboardSettingsRoute: OOrgSlugDashboardSettingsRoute,
    OOrgSlugDashboardTestimonialsRoute: OOrgSlugDashboardTestimonialsRoute,
  }

const OOrgSlugDashboardRouteRouteWithChildren =
  OOrgSlugDashboardRouteRoute._addFileChildren(
    OOrgSlugDashboardRouteRouteChildren,
  )

interface OOrgSlugRouteRouteChildren {
  OOrgSlugDashboardRouteRoute: typeof OOrgSlugDashboardRouteRouteWithChildren
  OOrgSlugIndexRoute: typeof OOrgSlugIndexRoute
}

const OOrgSlugRouteRouteChildren: OOrgSlugRouteRouteChildren = {
  OOrgSlugDashboardRouteRoute: OOrgSlugDashboardRouteRouteWithChildren,
  OOrgSlugIndexRoute: OOrgSlugIndexRoute,
}

const OOrgSlugRouteRouteWithChildren = OOrgSlugRouteRoute._addFileChildren(
  OOrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TestimonialsRouteRoute: TestimonialsRouteRouteWithChildren,
  SignOutRoute: SignOutRoute,
  OOrgSlugRouteRoute: OOrgSlugRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
